### ISSUE TITLE
Single-click on frame adjusts scrollpane unexpectedly

### ISSUE THREAD

**Issue by jfree** [bric3/fireplace#31]
To reproduce this issue:

- load a flame graph
- double-click on a frame to realign the flame graph on that frame, such that the minimap is somewhere in the middle of the flamegraph - as in the first screenshot below
- now single click on another frame and notice that the flame graph (and minimap) is realigned in an unexpected way - see the second screenshot below

![image](https://user-images.githubusercontent.com/1835893/158523299-b3870e6b-2c6f-4b24-b212-6ade5a135856.png)

After clicking on `IDATOutputStream.write(int)`:

![image](https://user-images.githubusercontent.com/1835893/158523374-c5e81e11-35d9-4809-b908-af545057be43.png)

**Comment by bric3** [comment]
Ah yes that was one of the bug. Thanks for fixing it !
