### ISSUE TITLE
Cannot select items in combo box

### ISSUE THREAD

**Issue by jfree** [bric3/fireplace#52]
I can open the combo boxes at the top of the `FirePlace` window but I cannot select anything (on MacOS at least).  It looks like maybe the flame graph is stealing the mouse events or focus, because as soon as the mouse pointer hits the flame graph area, the combobox gets closed. 

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1835893/161414941-0db300b7-62f8-4d1b-9f8a-5f55f24fd689.png">

**Comment by bric3** [comment]
Ah I saw that as well, if I move the mouse too fast, moving the mouse slower allow the menu to display and this allow to hover the combo box menu.

This may be related to the `mouseEnter` where the code is requesting focus, so that keyboard keys can be used.

**Comment by jfree** [comment]
This is fixed by https://github.com/bric3/fireplace/commit/18d633523de4a5500f9cdfee9705a050f3dc568a
